# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '__first__'),
        ('schools', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140, verbose_name='name')),
                ('surname_a', models.CharField(max_length=140, verbose_name='surname')),
                ('surname_b', models.CharField(blank=True, max_length=140, null=True, verbose_name='surname b')),
                ('born_date', models.DateField(null=True, verbose_name='date of birth')),
                ('address', models.CharField(max_length=140, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=140, null=True, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=140, null=True, verbose_name='mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added on')),
            ],
            options={
                'verbose_name': 'Adult',
                'verbose_name_plural': 'Adults',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140, verbose_name='name')),
                ('surname_a', models.CharField(max_length=140, verbose_name='surname')),
                ('surname_b', models.CharField(blank=True, max_length=140, null=True, verbose_name='surname b')),
                ('born_date', models.DateField(null=True, verbose_name='date of birth')),
                ('address', models.CharField(max_length=140, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=140, null=True, verbose_name='phone')),
                ('mobile', models.CharField(blank=True, max_length=140, null=True, verbose_name='mobile')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added on')),
                ('adults', models.ManyToManyField(blank=True, null=True, related_name='students', to='students.Adult', verbose_name='adults')),
                ('classes', models.ManyToManyField(blank=True, null=True, related_name='students', to='classes.Class', verbose_name='classes')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.School', verbose_name='school')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
