# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '__first__'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('surname_a', models.CharField(max_length=140)),
                ('surname_b', models.CharField(blank=True, max_length=140, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('surname_a', models.CharField(max_length=140)),
                ('surname_b', models.CharField(blank=True, max_length=140, null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('info', models.TextField(blank=True, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('adults', models.ManyToManyField(blank=True, null=True, related_name='students', to='students.Adult')),
                ('classes', models.ManyToManyField(blank=True, null=True, related_name='students', to='classes.Class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.School')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
