# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=140, verbose_name='name'),
        ),
    ]
