# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.IntegerField(default=1),
        ),
    ]
