# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_class_max_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(default=1, verbose_name='max students'),
        ),
    ]
