# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='added on')),
                ('info', models.TextField(blank=True, null=True, verbose_name='info')),
                ('name', models.CharField(max_length=140, verbose_name='name')),
                ('address', models.CharField(blank=True, max_length=140, null=True, verbose_name='address')),
                ('city', models.CharField(max_length=140, verbose_name='city')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
            },
        ),
    ]
